### ISSUE TITLE
Upgrade to use API version `2016-04-01`

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-azurerm#192]
Original Issue: https://github.com/coreos/tectonic-installer/issues/1315 / Original PR: https://github.com/jen20/riviera/pull/24

It appears that Azure's gradually removing support for the version of the DNS API that we're currently using  via the Riviera SDK `2015-05-04-preview`. Whilst we could switch over to using version `2016-04-01` it appears this requires some further refactoring where fields have changed.

The following PR's have been opened recently to switch these resources over to the Azure SDK for Go - which makes use of the updated API:

- [x] terraform-providers/terraform-provider-azurerm#188
- [x] terraform-providers/terraform-provider-azurerm#187
- [x] terraform-providers/terraform-provider-azurerm#186
- [x] terraform-providers/terraform-provider-azurerm#195
- [x] terraform-providers/terraform-provider-azurerm#185
- [x] terraform-providers/terraform-provider-azurerm#182
- [x] terraform-providers/terraform-provider-azurerm#181
- [x] terraform-providers/terraform-provider-azurerm#180
- [x] terraform-providers/terraform-provider-azurerm#179

Given these PR's exist - it looks like it could be quicker to switch these over to the Azure SDK for Go

**Comment by justaugustus** [comment]
@tombuildsstuff Thanks for your attention on this! Agreed that switching to Azure SDK for Go feels like the right route.

(Adding @alexsomesan, @s-urbaniak, @metral, @robszumski for visibility on the CoreOS side.)

**Comment by discordianfish** [comment]
That's a huge issue. This effectively means everyone managing their azure setup with terraform are unable to do any changes to their infrastructure right now. I don't even want to imagine what people going through right now who run prod stuff managed with terraform on azure and are effectively locked out of their infrastructure.
Has anyone contacted Azure to see if they could re-enable the APIs again?

**Comment by jdumars** [comment]
I'm looking into this now.

**Comment by tombuildsstuff** [comment]
Hey @justaugustus

> Has anyone contacted Azure to see if they could re-enable the APIs again?

That's a really good point - I've raised this internally at our end too and I'll post here when we've got an update (thanks @jdumars for requesting too)

> That's a huge issue. This effectively means everyone managing their azure setup with terraform are unable to do any (DNS) changes to their infrastructure right now. I don't even want to imagine what people going through right now who run prod stuff managed with terraform on azure and are effectively locked out of their infrastructure.

Apologies for the inconvenience here - I completely agree this is a major issue and we’re looking into it right now. Unfortunately the removal of the API version appears to be rolling out gradually and we were unaware this version was due to be removed. Since we were notified of the issue we’ve been working through upgrading to the new API version - and that should be completed in the next couple of hours.  We’ll also be double-checking the versions of the API’s we’re using as a result of this for any further deprecations.

Apologies once again for the inconvenience - as I mentioned above we should have a fix for this completed later today.

Thanks!

**Comment by jdumars** [comment]
Waiting to confirm on this, but I believe the issue has been fixed in Terraform master, and will be closed in the next update.

**Comment by tombuildsstuff** [comment]
Hey @justaugustus @discordianfish @jdumars 

> Waiting to confirm on this, but I believe the issue has been fixed in Terraform master, and will be closed in the next update.

Correct - I was just running the entire test suite before releasing :)

I've just released version 0.1.4 of the Terraform AzureRM Provider which switches over to using version `2016-04-01` of the Azure DNS API's - which is available in Terraform 0.10-rc1 (and can be used in Terraform 0.9 by updating the `~.terraformrc` file to reference the downloaded provider).

Would it be possible for you to take a look?

Thanks!

cc @alexsomesan, @s-urbaniak, @metral, @robszumski

**Comment by justaugustus** [comment]
Thank you so much for chasing this down, @tombuildsstuff!
CoreOS team will give this a try and report back when we have an opportunity.

**Comment by alexsomesan** [comment]
@justaugustus I will test this out tomorrow

**Comment by tombuildsstuff** [comment]
Given the fix for this issue has been released - I'm going to close this issue for the moment. However please feel free to re-open it if there's still an issue here :)
